#!/usr/bin/env python3
"""kb-index.py — regenerate INDEX.md from the front matter of every KB document.

INDEX.md is rung 1 of the retrieval ladder (CLAUDE.md §7): one line per document,
always the first read, small enough to load whole. It is GENERATED — do not hand-edit.

Deliberately dependency-free: the front matter this KB uses is a flat subset of YAML
(scalars, [a, b] inline lists, and "- item" block lists), so it is parsed here rather
than pulling in PyYAML. If the front matter ever needs nested structures, switch to
PyYAML instead of extending this parser.

Usage:  python3 tools/kb-index.py [kb-root]      (default: the repo root)
"""

import os
import sys
import re

SKIP_DIRS = {".git", "inbox", "log", "tools", "benchmark", "sources"}
SKIP_FILES = {"CLAUDE.md", "INDEX.md", "README.md", "LICENSE"}

FIELDS = ("id", "title", "status", "platform", "applies_to", "tags", "related",
          "verified_on")

# Order documents by status so the antidotes to model priors sort first — CLAUDE.md §6
# calls myth documents "high-priority reading".
STATUS_ORDER = ["myth", "disputed", "tested", "source", "manual", "inferred",
                "assumed", "obsolete"]


def parse_front_matter(path):
    """Return a dict of the document's front matter, or None if it has none."""
    with open(path, encoding="utf-8") as fh:
        if fh.readline().strip() != "---":
            return None
        lines = []
        for line in fh:
            if line.strip() == "---":
                break
            lines.append(line.rstrip("\n"))
        else:
            return None  # unterminated front matter

    meta, key = {}, None
    for line in lines:
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith(("  - ", "- ")):          # block list item
            if key:
                meta.setdefault(key, []).append(line.split("- ", 1)[1].strip().strip('"'))
            continue
        m = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
        if not m:
            continue
        key, value = m.group(1), m.group(2).strip()
        if value == "":
            meta[key] = []                            # block list follows
        elif value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            meta[key] = [v.strip() for v in inner.split(",") if v.strip()]
        else:
            meta[key] = value.strip('"')
    return meta


def collect(root):
    docs, problems = [], []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in sorted(filenames):
            if not name.endswith(".md") or name in SKIP_FILES:
                continue
            path = os.path.join(dirpath, name)
            rel = os.path.relpath(path, root)
            meta = parse_front_matter(path)
            if meta is None:
                problems.append(f"{rel}: no front matter")
                continue
            for required in ("id", "title", "status", "platform"):
                if not meta.get(required):
                    problems.append(f"{rel}: missing '{required}'")
            meta["_path"] = rel
            docs.append(meta)
    return docs, problems


def as_list(value):
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def check_links(docs, problems):
    by_id = {d.get("id"): d for d in docs if d.get("id")}
    seen = {}
    for d in docs:
        did = d.get("id")
        if did in seen:
            problems.append(f"{d['_path']}: duplicate id {did} (also {seen[did]})")
        seen[did] = d["_path"]
    for d in docs:
        for target in as_list(d.get("related")):
            if target not in by_id:
                problems.append(f"{d['_path']}: related -> {target} does not exist")
            elif d.get("id") not in as_list(by_id[target].get("related")):
                problems.append(
                    f"{d['_path']}: related -> {target} is not reciprocated")


ROOT = ["."]


def render(docs):
    out = ["# INDEX",
           "",
           "**GENERATED by `tools/kb-index.py`. Do not hand-edit.**",
           "",
           "Rung 1 of the retrieval ladder (`CLAUDE.md` §7). Find the document here, then",
           "open exactly that document — not the directory.",
           "",
           f"{len(docs)} documents.",
           ""]

    order = {s: i for i, s in enumerate(STATUS_ORDER)}
    docs = sorted(docs, key=lambda d: (order.get(d.get("status"), 99), d.get("id", "")))

    out += ["| ID | Title | Status | Platform | Tags | Path |",
            "|---|---|---|---|---|---|"]
    for d in docs:
        out.append("| `{id}` | {title} | `{status}` | {plat} | {tags} | `{path}` |".format(
            id=d.get("id", "?"),
            title=d.get("title", "?").replace("|", "\\|"),
            status=d.get("status", "?"),
            plat=", ".join(as_list(d.get("platform"))),
            tags=", ".join(as_list(d.get("tags"))[:8]),
            path=d["_path"]))

    out += ["", "## By status", ""]
    for status in STATUS_ORDER:
        group = [d for d in docs if d.get("status") == status]
        if group:
            out.append(f"- **{status}** ({len(group)}): "
                       + ", ".join(f"`{d.get('id')}`" for d in group))

    out += ["", "## Reference material (`sources/`)", "",
            "Catalogue entries, not documents — no front matter, cited by `SRC-` id.", ""]
    src_root = os.path.join(ROOT[0], "sources")
    if os.path.isdir(src_root):
        for name in sorted(os.listdir(src_root)):
            if not name.endswith(".md"):
                continue
            with open(os.path.join(src_root, name), encoding="utf-8") as fh:
                for line in fh:
                    m = re.match(r"^#{2,3}\s+(SRC-\d+)\s+—\s+(.*)$", line.strip())
                    if m:
                        out.append(f"- `{m.group(1)}` — {m.group(2)}  ·  `sources/{name}`")

    out += ["", "## By project", ""]
    projects = {}
    for d in docs:
        for p in as_list(d.get("applies_to")):
            projects.setdefault(p, []).append(d.get("id"))
    for p in sorted(projects):
        out.append(f"- **{p}**: " + ", ".join(f"`{i}`" for i in sorted(projects[p])))

    out.append("")
    return "\n".join(out)


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    ROOT[0] = root
    docs, problems = collect(root)
    check_links(docs, problems)

    with open(os.path.join(root, "INDEX.md"), "w", encoding="utf-8") as fh:
        fh.write(render(docs))

    print(f"INDEX.md: {len(docs)} documents")
    if problems:
        print(f"\n{len(problems)} problem(s):")
        for p in problems:
            print(f"  {p}")
        return 1
    print("no problems")
    return 0


if __name__ == "__main__":
    sys.exit(main())
